export const china = [
    { value: "安徽省", label: "安徽省 — Anhui Sheng" },
    { value: "澳门", label: "澳门 — Macau" },
    { value: "北京市", label: "北京市 — Beijing Shi" },
    { value: "重庆市", label: "重庆市 — Chongqing Shi" },
    { value: "福建省", label: "福建省 — Fujian Sheng" },
    { value: "甘肃省", label: "甘肃省 — Gansu Sheng" },
    { value: "广东省", label: "广东省 — Guangdong Sheng" },
    { value: "广西壮族自治区", label: "广西 — Guangxi Zhuangzuzizhiqu" },
    { value: "贵州省", label: "贵州省 — Guizhou Sheng" },
    { value: "海南省", label: "海南省 — Hainan Sheng" },
    { value: "河北省", label: "河北省 — Hebei Sheng" },
    { value: "河南省", label: "河南省 — Henan Sheng" },
    { value: "黑龙江省", label: "黑龙江省 — Heilongjiang Sheng" },
    { value: "湖北省", label: "湖北省 — Hubei Sheng" },
    { value: "湖南省", label: "湖南省 — Hunan Sheng" },
    { value: "吉林省", label: "吉林省 — Jilin Sheng" },
    { value: "江苏省", label: "江苏省 — Jiangsu Sheng" },
    { value: "江西省", label: "江西省 — Jiangxi Sheng" },
    { value: "辽宁省", label: "辽宁省 — Liaoning Sheng" },
    { value: "内蒙古自治区", label: "内蒙古 — Neimenggu Zizhiqu" },
    { value: "宁夏回族自治区", label: "宁夏 — Ningxia Huizuzizhiqu" },
    { value: "青海省", label: "青海省 — Qinghai Sheng" },
    { value: "山东省", label: "山东省 — Shandong Sheng" },
    { value: "山西省", label: "山西省 — Shanxi Sheng" },
    { value: "陕西省", label: "陕西省 — Shaanxi Sheng" },
    { value: "上海市", label: "上海市 — Shanghai Shi" },
    { value: "四川省", label: "四川省 — Sichuan Sheng" },
    { value: "台湾", label: "台湾 — Taiwan" },
    { value: "天津市", label: "天津市 — Tianjin Shi" },
    { value: "西藏自治区", label: "西藏 — Xizang Zizhiqu" },
    { value: "香港", label: "香港 — Hong Kong" },
    { value: "新疆维吾尔自治区", label: "新疆 — Xinjiang Weiwuerzizhiqu" },
    { value: "云南省", label: "云南省 — Yunnan Sheng" },
    { value: "浙江省", label: "浙江省 — Zhejiang Sheng" },
]