export const egypt = [

    { value: "أسوان", label: "أسوان — Aswan Governorate" },
    { value: "أسيوط", label: "أسيوط — Asyut Governorate" },
    { value: "الإسكندرية", label: "الإسكندرية — Alexandria Governorate" },
    { value: "الإسماعيلية", label: "الإسماعيلية — Ismailia Governorate" },
    { value: "الأقصر", label: "الأقصر — Luxor Governorate" },
    { value: "البحر الأحمر", label: "البحر الأحمر — Red Sea Governorate" },
    { value: "البحيرة", label: "البحيرة — El Beheira Governorate" },
    { value: "الجيزة", label: "الجيزة — Giza Governorate" },
    { value: "الدقهلية", label: "الدقهلية — Dakahlia Governorate" },
    { value: "السويس", label: "السويس — Suez Governorate" },
    { value: "الشرقية", label: "الشرقية — Ash Sharqia Governorate" },
    { value: "الغربية", label: "الغربية — Gharbia Governorate" },
    { value: "الفيوم", label: "الفيوم — Faiyum Governorate" },
    { value: "القاهرة", label: "القاهرة — Cairo Governorate" },
    { value: "القليوبية", label: "القليوبية — Qalyubia Governorate" },
    { value: "المنوفية", label: "المنوفية — Menofia Governorate" },
    { value: "المنيا", label: "المنيا — Menia Governorate" },
    { value: "الوادي الجديد", label: "الوادي الجديد — New Valley Governorate" },
    { value: "بني سويف", label: "بني سويف — Beni Suef Governorate" },
    { value: "بورسعيد", label: "بورسعيد — Port Said Governorate" },
    { value: "جنوب سيناء", label: "جنوب سيناء — South Sinai Governorate" },
    { value: "دمياط", label: "دمياط — Damietta Governorate" },
    { value: "سوهاج", label: "سوهاج — Sohag Governorate" },
    { value: "شمال سيناء", label: "شمال سيناء — North Sinai Governorate" },
    { value: "قنا", label: "قنا — Qena Governorate" },
    { value: "كفر الشيخ", label: "كفر الشيخ — Kafr El Sheikh Governorate" },
    { value: "مطروح", label: "مطروح — Matrouh Governorate" },
]