export const elsalvador = [
    { value: "Ahuachapan", label: "Ahuachapán" },
    { value: "Cabanas", label: "Cabañas" },
    { value: "Calatenango", label: "Chalatenango" },
    { value: "Cuscatlan", label: "Cuscatlán" },
    { value: "La Libertad", label: "La Libertad" },
    { value: "La Paz", label: "La Paz" },
    { value: "La Union", label: "La Unión" },
    { value: "Morazan", label: "Morazán" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "San Salvador", label: "San Salvador" },
    { value: "San Vicente", label: "San Vicente" },
    { value: "Santa Ana", label: "Santa Ana" },
    { value: "Sonsonate", label: "Sonsonate" },
    { value: "Usulutan", label: "Usulután" },
]