export const iraq = [
    { value: "Al Anbar Governorate", label: "Al Anbar Governorate" },
    { value: "Basra Governorate", label: "Basra Governorate" },
    { value: "Muthanna Governorate", label: "Muthanna Governorate" },
    { value: "Al-Qadisiyah Governorate", label: "Al-Qadisiyah Governorate" },
    { value: "Najaf Governorate", label: "Najaf Governorate" },
    { value: "Erbil Governorate", label: "Erbil Governorate" },
    { value: "Sulaymaniyah Governorate", label: "Sulaymaniyah Governorate" },
    { value: "Babil Governorate", label: "Babil Governorate" },
    { value: "Baghdad Governorate", label: "Baghdad Governorate" },
    { value: "Dohuk Governorate", label: "Dohuk Governorate" },
    { value: "Dhi Qar Governorate", label: "Dhi Qar Governorate" },
    { value: "Diyala Governorate", label: "Diyala Governorate" },
    { value: "Karbala Governorate", label: "Karbala Governorate" },
    { value: "Kirkuk Governorate", label: "Kirkuk Governorate" },
    { value: "Maysan Governorate", label: "Maysan Governorate" },
    { value: "Nineveh Governorate", label: "Nineveh Governorate" },
    { value: "Saladin Governorate", label: "Saladin Governorate" },
    { value: "Wasit Governorate", label: "Wasit Governorate" },
]