export const kazakhstan = [
    { value: "Almaty", label: "Almaty" },
    { value: "Astana", label: "Astana" },
    { value: "Almatinskaya oblast'", label: "Almatinskaya oblast'" },
    { value: "Akmolinskaya oblast'", label: "Akmolinskaya oblast'" },
    { value: "Aktyubinskaya oblast'", label: "Aktyubinskaya oblast'" },
    { value: "Atyrauskaya oblast'", label: "Atyrauskaya oblast'" },
    { value: "Baykonyr", label: "Baykonyr" },
    { value: "Zapadno-Kazakhstanskaya oblast'", label: "Zapadno-Kazakhstanskaya oblast'" },
    { value: "Mangistauskaya oblast'", label: "Mangistauskaya oblast'" },
    { value: "Yuzhno-Kazakhstankaya oblast'", label: "Yuzhno-Kazakhstankaya oblast'" },
    { value: "Pavlodarskaya oblast'", label: "Pavlodarskaya oblast'" },
    { value: "Karagandinskaya oblast'", label: "Karagandinskaya oblast'" },
    { value: "Kostanayskaya oblast'", label: "Kostanayskaya oblast'" },
    { value: "Kyzylordinskaya oblast'", label: "Kyzylordinskaya oblast'" },
    { value: "Vostochno-Kazakhstanskaya oblast'", label: "Vostochno-Kazakhstanskaya oblast'" },
    { value: "Severo-Kazakhstanskaya oblast'", label: "Severo-Kazakhstanskaya oblast'" },
    { value: "Zhambylskaya oblast'", label: "Zhambylskaya oblast'" },
]