export const mexico = [
    { value: "Ags.", label: "Aguascalientes" },
    { value: "B.C.", label: "Baja California" },
    { value: "B.C.S.", label: "Baja California Sur" },
    { value: "Camp.", label: "Campeche" },
    { value: "Chis.", label: "Chiapas" },
    { value: "Chih.", label: "Chihuahua" },
    { value: "CDMX", label: "Ciudad de México" },
    { value: "Coah.", label: "Coahuila de Zaragoza" },
    { value: "Col.", label: "Colima" },
    { value: "Dgo.", label: "Durango" },
    { value: "Méx.", label: "Estado de México" },
    { value: "Gto.", label: "Guanajuato" },
    { value: "Gro.", label: "Guerrero" },
    { value: "Hgo.", label: "Hidalgo" },
    { value: "Jal.", label: "Jalisco" },
    { value: "Mich.", label: "Michoacán" },
    { value: "Mor.", label: "Morelos" },
    { value: "Nay.", label: "Nayarit" },
    { value: "N.L.", label: "Nuevo León" },
    { value: "Oax.", label: "Oaxaca" },
    { value: "Pue.", label: "Puebla" },
    { value: "Qro.", label: "Querétaro" },
    { value: "Q.R.", label: "Quintana Roo" },
    { value: "S.L.P.", label: "San Luis Potosí" },
    { value: "Sin.", label: "Sinaloa" },
    { value: "Son.", label: "Sonora" },
    { value: "Tab.", label: "Tabasco" },
    { value: "Tamps.", label: "Tamaulipas" },
    { value: "Tlax.", label: "Tlaxcala" },
    { value: "Ver.", label: "Veracruz" },
    { value: "Yuc.", label: "Yucatán" },
    { value: "Zac.", label: "Zacatecas" },
]