export const mongolia = [
    { value: "Ulaanbaatar", label: "Ulaanbaatar" },
    { value: "Arkhangai Province", label: "Arkhangai Province" },
    { value: "Bayankhongor Province", label: "Bayankhongor Province" },
    { value: "Bayan-Ölgii Province", label: "Bayan-Ölgii Province" },
    { value: "Bulgan Province", label: "Bulgan Province" },
    { value: "Darkhan-Uul Province", label: "Darkhan-Uul Province" },
    { value: "Dornod Province", label: "Dornod Province" },
    { value: "Dornogovi Province", label: "Dornogovi Province" },
    { value: "Dundgovi Province", label: "Dundgovi Province" },
    { value: "Zavkhan Province", label: "Zavkhan Province" },
    { value: "Govi-Altai Province", label: "Govi-Altai Province" },
    { value: "Govisümber Province", label: "Govisümber Province" },
    { value: "Khentii Province", label: "Khentii Province" },
    { value: "Khovd Province", label: "Khovd Province" },
    { value: "Khövsgöl Province", label: "Khövsgöl Province" },
    { value: "Ömnögovi Province", label: "Ömnögovi Province" },
    { value: "Orkhon Province", label: "Orkhon Province" },
    { value: "Övörkhangai Province", label: "Övörkhangai Province" },
    { value: "Selenge Province", label: "Selenge Province" },
    { value: "Sükhbaatar Province", label: "Sükhbaatar Province" },
    { value: "Töv Province", label: "Töv Province" },
    { value: "Uvs Province", label: "Uvs Province" },
]