export const nauru = [
    { value: "Aiwo District", label: "Aiwo District" },
    { value: "Anabar District", label: "Anabar District" },
    { value: "Anetan District", label: "Anetan District" },
    { value: "Anibare District", label: "Anibare District" },
    { value: "Baiti District", label: "Baiti District" },
    { value: "Boe District", label: "Boe District" },
    { value: "Buada District", label: "Buada District" },
    { value: "Denigomodu District", label: "Denigomodu District" },
    { value: "Ewa District", label: "Ewa District" },
    { value: "Ijuw District", label: "Ijuw District" },
    { value: "Meneng District", label: "Meneng District" },
    { value: "Nibok District", label: "Nibok District" },
    { value: "Uaboe District", label: "Uaboe District" },
    { value: "Yaren District", label: "Yaren District" },
]