export const nicaragua = [
    { value: "Boaco", label: "Boaco" },
    { value: "Carazo", label: "Carazo" },
    { value: "Chinandega", label: "Chinandega" },
    { value: "Chontales", label: "Chontales" },
    { value: "Estelí", label: "Estelí" },
    { value: "Granada", label: "Granada" },
    { value: "Jinotega", label: "Jinotega" },
    { value: "León", label: "León" },
    { value: "Madriz", label: "Madriz" },
    { value: "Managua", label: "Managua" },
    { value: "Masaya", label: "Masaya" },
    { value: "Matagalpa", label: "Matagalpa" },
    { value: "Nueva Segovia", label: "Nueva Segovia" },
    { value: "Región Autónoma de la Costa Caribe Norte", label: "Región Autónoma de la Costa Caribe Norte" },
    { value: "Región Autónoma de la Costa Caribe Sur", label: "Región Autónoma de la Costa Caribe Sur" },
    { value: "Río San Juan", label: "Río San Juan" },
    { value: "Rivas", label: "Rivas" },
]