export const papuanewguinea = [
    { value: "National Capital District", label: "National Capital District" },
    { value: "Central", label: "Central" },
    { value: "Chimbu", label: "Chimbu" },
    { value: "Eastern Highlands", label: "Eastern Highlands" },
    { value: "East New Britain", label: "East New Britain" },
    { value: "East Sepik", label: "East Sepik" },
    { value: "Enga", label: "Enga" },
    { value: "Gulf", label: "Gulf" },
    { value: "Hela", label: "Hela" },
    { value: "Jiwaka", label: "Jiwaka" },
    { value: "Madang", label: "Madang" },
    { value: "Manus", label: "Manus" },
    { value: "Milne Bay", label: "Milne Bay" },
    { value: "Morobe", label: "Morobe" },
    { value: "New Ireland", label: "New Ireland" },
    { value: "Northern", label: "Northern" },
    { value: "West Sepik", label: "West Sepik" },
    { value: "Southern Highlands", label: "Southern Highlands" },
    { value: "Western", label: "Western" },
    { value: "Western Highlands", label: "Western Highlands" },
    { value: "West New Britain", label: "West New Britain" },
    { value: "Bougainville", label: "Bougainville" },
]