export const peru = [
    { value: "Municipalidad Metropolitana de Lima", label: "Municipalidad Metropolitana de Lima" },
    { value: "Amazonas", label: "Amazonas" },
    { value: "Ancash", label: "Ancash" },
    { value: "Apurímac", label: "Apurímac" },
    { value: "Arequipa", label: "Arequipa" },
    { value: "Ayacucho", label: "Ayacucho" },
    { value: "Cajamarca", label: "Cajamarca" },
    { value: "Cusco", label: "Cusco" },
    { value: "El Callao", label: "El Callao" },
    { value: "Huancavelica", label: "Huancavelica" },
    { value: "Huánuco", label: "Huánuco" },
    { value: "Ica", label: "Ica" },
    { value: "Junín", label: "Junín" },
    { value: "La Libertad", label: "La Libertad" },
    { value: "Lambayeque", label: "Lambayeque" },
    { value: "Lima", label: "Lima" },
    { value: "Loreto", label: "Loreto" },
    { value: "Madre de Dios", label: "Madre de Dios" },
    { value: "Moquegua", label: "Moquegua" },
    { value: "Pasco", label: "Pasco" },
    { value: "Piura", label: "Piura" },
    { value: "Puno", label: "Puno" },
    { value: "San Martín", label: "San Martín" },
    { value: "Tacna", label: "Tacna" },
    { value: "Tumbes", label: "Tumbes" },
    { value: "Ucayali", label: "Ucayali" },
]