export const philippines = [
    { value: "Abra", label: "Abra" },
    { value: "Agusan del Norte", label: "Agusan del Norte" },
    { value: "Agusan del Sur", label: "Agusan del Sur" },
    { value: "Aklan", label: "Aklan" },
    { value: "Albay", label: "Albay" },
    { value: "Antique", label: "Antique" },
    { value: "Apayao", label: "Apayao" },
    { value: "Aurora", label: "Aurora" },
    { value: "Basilan", label: "Basilan" },
    { value: "Bataan", label: "Bataan" },
    { value: "Batanes", label: "Batanes" },
    { value: "Batangas", label: "Batangas" },
    { value: "Benguet", label: "Benguet" },
    { value: "Biliran", label: "Biliran" },
    { value: "Bohol", label: "Bohol" },
    { value: "Bukidnon", label: "Bukidnon" },
    { value: "Bulacan", label: "Bulacan" },
    { value: "Cagayan", label: "Cagayan" },
    { value: "Camarines Norte", label: "Camarines Norte" },
    { value: "Camarines Sur", label: "Camarines Sur" },
    { value: "Camiguin", label: "Camiguin" },
    { value: "Capiz", label: "Capiz" },
    { value: "Catanduanes", label: "Catanduanes" },
    { value: "Cavite", label: "Cavite" },
    { value: "Cebu", label: "Cebu" },
    { value: "Compostela Valley", label: "Compostela Valley" },
    { value: "Cotabato", label: "Cotabato" },
    { value: "Davao del Norte", label: "Davao del Norte" },
    { value: "Davao del Sur", label: "Davao del Sur" },
    { value: "Davao Occidental", label: "Davao Occidental" },
    { value: "Davao Oriental", label: "Davao Oriental" },
    { value: "Dinagat Islands", label: "Dinagat Islands" },
    { value: "Eastern Samar", label: "Eastern Samar" },
    { value: "Guimaras", label: "Guimaras" },
    { value: "Ifugao", label: "Ifugao" },
    { value: "Ilocos Norte", label: "Ilocos Norte" },
    { value: "Ilocos Sur", label: "Ilocos Sur" },
    { value: "Iloilo", label: "Iloilo" },
    { value: "Isabela", label: "Isabela" },
    { value: "Kalinga", label: "Kalinga" },
    { value: "La Union", label: "La Union" },
    { value: "Laguna", label: "Laguna" },
    { value: "Lanao del Norte", label: "Lanao del Norte" },
    { value: "Lanao del Sur", label: "Lanao del Sur" },
    { value: "Leyte", label: "Leyte" },
    { value: "Maguindanao", label: "Maguindanao" },
    { value: "Marinduque", label: "Marinduque" },
    { value: "Masbate", label: "Masbate" },
    { value: "Metro Manila", label: "Metro Manila" },
    { value: "Mindoro Occidental", label: "Mindoro Occidental" },
    { value: "Mindoro Oriental", label: "Mindoro Oriental" },
    { value: "Misamis Occidental", label: "Misamis Occidental" },
    { value: "Misamis Oriental", label: "Misamis Oriental" },
    { value: "Mountain Province", label: "Mountain Province" },
    { value: "Negros Occidental", label: "Negros Occidental" },
    { value: "Negros Oriental", label: "Negros Oriental" },
    { value: "Northern Samar", label: "Northern Samar" },
    { value: "Nueva Ecija", label: "Nueva Ecija" },
    { value: "Nueva Vizcaya", label: "Nueva Vizcaya" },
    { value: "Palawan", label: "Palawan" },
    { value: "Pampanga", label: "Pampanga" },
    { value: "Pangasinan", label: "Pangasinan" },
    { value: "Quezon Province", label: "Quezon Province" },
    { value: "Quirino", label: "Quirino" },
    { value: "Rizal", label: "Rizal" },
    { value: "Romblon", label: "Romblon" },
    { value: "Samar", label: "Samar" },
    { value: "Sarangani", label: "Sarangani" },
    { value: "Siquijor", label: "Siquijor" },
    { value: "Sorsogon", label: "Sorsogon" },
    { value: "South Cotabato", label: "South Cotabato" },
    { value: "Southern Leyte", label: "Southern Leyte" },
    { value: "Sultan Kudarat", label: "Sultan Kudarat" },
    { value: "Sulu", label: "Sulu" },
    { value: "Surigao del Norte", label: "Surigao del Norte" },
    { value: "Surigao del Sur", label: "Surigao del Sur" },
    { value: "Tarlac", label: "Tarlac" },
    { value: "Tawi-Tawi", label: "Tawi-Tawi" },
    { value: "Zambales", label: "Zambales" },
    { value: "Zamboanga del Norte", label: "Zamboanga del Norte" },
    { value: "Zamboanga del Sur", label: "Zamboanga del Sur" },
    { value: "Zamboanga Sibuguey", label: "Zamboanga Sibuguey" },
]