export const russia = [
    { value: "Алтайский край", label: "Алтайский край — Altayskiy kray" },
    { value: "Амурская область", label: "Амурская область — Amurskaya oblast'" },
    { value: "Архангельская область", label: "Архангельская область — Arkhangelskaya oblast'" },
    { value: "Астраханская область", label: "Астраханская область — Astrakhanskaya oblast'" },
    { value: "Белгородская область", label: "Белгородская область — Belgorodskaya oblast'" },
    { value: "Брянская область", label: "Брянская область — Bryanskaya oblast'" },
    { value: "Владимирская область", label: "Владимирская область — Vladimirskaya oblast'" },
    { value: "Волгоградская область", label: "Волгоградская область — Volgogradskaya oblast'" },
    { value: "Вологодская область", label: "Вологодская область — Vologodskaya oblast'" },
    { value: "Воронежская область", label: "Воронежская область — Voronezhskaya oblast'" },
    { value: "Еврейская автономная область", label: "Еврейская автономная область — Evreyskaya avtonomnaya oblast'" },
    { value: "Забайкальский край", label: "Забайкальский край — Zabaykalskiy kray" },
    { value: "Ивановская область", label: "Ивановская область — Ivanovskaya oblast'" },
    { value: "Иркутская область", label: "Иркутская область — Irkutskaya oblast'" },
    { value: "Кабардино-Балкарская Республика", label: "Кабардино-Балкарская Республика — Kabardino-Balkarskaya Republits" },
    { value: "Калининградская область", label: "Калининградская область — Kaliningradskaya oblast'" },
    { value: "Калужская область", label: "Калужская область — Kaluzhskaya oblast'" },
    { value: "Камчатский край", label: "Камчатский край — Kamchatskiy kray" },
    { value: "Карачаево-Черкесская Республика", label: "Карачаево-Черкесская Республика — Karachaevo-Cherkesskaya Republits" },
    { value: "Кемеровская область", label: "Кемеровская область — Kemerovskaya oblast'" },
    { value: "Кировская область", label: "Кировская область — Kirovskaya oblast'" },
    { value: "Костромская область", label: "Костромская область — Kostromskaya oblast'" },
    { value: "Краснодарский край", label: "Краснодарский край — Krasnodarskiy kray" },
    { value: "Красноярский край", label: "Красноярский край — Krasnoyarskiy kray" },
    { value: "Курганская область", label: "Курганская область — Kurganskaya oblast'" },
    { value: "Курская область", label: "Курская область — Kurskaya oblast'" },
    { value: "Ленинградская область", label: "Ленинградская область — Leningradskaya oblast'" },
    { value: "Липецкая область", label: "Липецкая область — Lipetskaya oblast'" },
    { value: "Магаданская область", label: "Магаданская область — Magadanskaya oblast'" },
    { value: "Москва", label: "Москва — Moskva" },
    { value: "Московская область", label: "Московская область — Moskovskaya oblast'" },
    { value: "Мурманская область", label: "Мурманская область — Murmanskaya oblast'" },
    { value: "Ненецкий автономный округ", label: "Ненецкий автономный округ — Nenetskiy" },
    { value: "Нижегородская область", label: "Нижегородская область — Nizhegorodskaya oblast'" },
    { value: "Новгородская область", label: "Новгородская область — Novgorodskaya oblast'" },
    { value: "Новосибирская область", label: "Новосибирская область — Novosibirskaya oblast'" },
    { value: "Омская область", label: "Омская область — Omskaya oblast'" },
    { value: "Оренбургская область", label: "Оренбургская область — Orenburgskaya oblast'" },
    { value: "Орловская область", label: "Орловская область — Orlovskaya oblast'" },
    { value: "Пензенская область", label: "Пензенская область — Penzenskaya oblast'" },
    { value: "Пермский край", label: "Пермский край — Permskiy kray" },
    { value: "Приморский край", label: "Приморский край — Primorskiy kray" },
    { value: "Псковская область", label: "Псковская область — Pskovskaya oblast'" },
    { value: "Республика Адыгея", label: "Республика Адыгея — Respublika Adygeya" },
    { value: "Республика Алтай", label: "Республика Алтай — Altay Republits" },
    { value: "Республика Башкортостан", label: "Республика Башкортостан — Bashkortostan Republits" },
    { value: "Республика Бурятия", label: "Республика Бурятия — Buryatiya Republits" },
    { value: "Республика Дагестан", label: "Республика Дагестан — Dagestan Republits" },
    { value: "Республика Ингушетия", label: "Республика Ингушетия — Ingushetiya Republits" },
    { value: "Республика Калмыкия", label: "Республика Калмыкия — Respublika Kalmykiya" },
    { value: "Республика Карелия", label: "Республика Карелия — Kareliya Republits" },
    { value: "Республика Коми", label: "Республика Коми — Komi Republits" },
    { value: "Автономна Республіка Крим", label: "Республика Крым — Respublika Krym" },
    { value: "Республика Марий Эл", label: "Республика Марий Эл — Respublika Mariy El" },
    { value: "Республика Мордовия", label: "Республика Мордовия — Respublika Mordoviya" },
    { value: "Республика Саха (Якутия)", label: "Республика Саха (Якутия) — Sakha (Yakutiya) Republits" },
    { value: "Республика Северная Осетия-Алания", label: "Республика Северная Осетия-Алания — Respublika Severnaya Osetiya-Alaniya" },
    { value: "Республика Татарстан", label: "Республика Татарстан — Respublika Tatarstan" },
    { value: "Республика Тыва", label: "Республика Тыва — Tyva Republits" },
    { value: "Республика Удмуртия", label: "Республика Удмуртия — Respublika Udmurtiya" },
    { value: "Республика Хакасия", label: "Республика Хакасия — Khakasiya Republits" },
    { value: "Ростовская область", label: "Ростовская область — Rostovskaya oblast'" },
    { value: "Рязанская область", label: "Рязанская область — Ryazanskaya oblast'" },
    { value: "Самарская область", label: "Самарская область — Samarskaya oblast'" },
    { value: "Санкт-Петербург", label: "Санкт-Петербург — Sankt-Peterburg" },
    { value: "Саратовская область", label: "Саратовская область — Saratovskaya oblast'" },
    { value: "Сахалинская область", label: "Сахалинская область — Sakhalinskaya oblast'" },
    { value: "Свердловская область", label: "Свердловская область — Sverdlovskaya oblast'" },
    { value: "Севастополь", label: "Севастополь — Sevastopol'" },
    { value: "Смоленская область", label: "Смоленская область — Smolenskaya oblast'" },
    { value: "Ставропольский край", label: "Ставропольский край — Stavropolskiy kray" },
    { value: "Тамбовская область", label: "Тамбовская область — Tambovskaya oblast'" },
    { value: "Тверская область", label: "Тверская область — Tverskaya oblast'" },
    { value: "Томская область", label: "Томская область — Tomskaya oblast'" },
    { value: "Тульская область", label: "Тульская область — Tulskaya oblast'" },
    { value: "Тюменская область", label: "Тюменская область — Tyumenskaya oblast'" },
    { value: "Ульяновская область", label: "Ульяновская область — Ulyanovskaya oblast'" },
    { value: "Хабаровский край", label: "Хабаровский край — Khabarovskiy kray" },
    { value: "Ханты-Мансийский автономный округ", label: "Ханты-Мансийский автономный округ — Khanty-Mansiyskiy avtonomnyy okrug" },
    { value: "Челябинская область", label: "Челябинская область — Chelyabinskaya oblast'" },
    { value: "Чеченская Республика", label: "Чеченская Республика — Chechenskaya Republits" },
    { value: "Чувашская Республика", label: "Чувашская Республика — Chuvashia" },
    { value: "Чукотский автономный округ", label: "Чукотский автономный округ — Chukotskiy" },
    { value: "Ямало-Ненецкий автономный округ", label: "Ямало-Ненецкий автономный округ — Yamalo-Nenetskiy" },
    { value: "Ярославская область", label: "Ярославская область — Yaroslavskaya oblast'" },
]