export const somalia = [
    { value: "AD", label: "Awdal" },
    { value: "BK", label: "Bakool" },
    { value: "BN", label: "Banaadir" },
    { value: "BR", label: "Bari" },
    { value: "BY", label: "Bay" },
    { value: "GG", label: "Galguduud" },
    { value: "GD", label: "Gedo" },
    { value: "HR", label: "Hiiraan" },
    { value: "JD", label: "Jubbada Dhexe" },
    { value: "JH", label: "Jubbada Hoose" },
    { value: "MD", label: "Mudug" },
    { value: "NG", label: "Nugaal" },
    { value: "SG", label: "Sanaag" },
    { value: "SD", label: "Shabeellaha Dhexe" },
    { value: "SH", label: "Shabeellaha Hoose" },
    { value: "SL", label: "Sool" },
    { value: "TG", label: "Togdheer" },
    { value: "WG", label: "Woqooyi Galbeed" },
]