export const southkorea = [
    { value: "강원도", label: "강원 — Gangwon-do" },
    { value: "경기도", label: "경기 — Gyeonggi-do" },
    { value: "경상남도", label: "경남 — Gyeongsangnam-do" },
    { value: "경상북도", label: "경북 — Gyeongsangbuk-do" },
    { value: "광주광역시", label: "광주 — Gwangju" },
    { value: "대구광역시", label: "대구 — Daegu" },
    { value: "대전광역시", label: "대전 — Daejeon" },
    { value: "부산광역시", label: "부산 — Busan" },
    { value: "서울특별시", label: "서울 — Seoul" },
    { value: "세종특별자치시", label: "세종 — Sejong" },
    { value: "울산광역시", label: "울산 — Ulsan" },
    { value: "인천광역시", label: "인천 — Incheon" },
    { value: "전라남도", label: "전남 — Jeollanam-do" },
    { value: "전라북도", label: "전북 — Jeollabuk-do" },
    { value: "제주특별자치도", label: "제주 — Jeju-do" },
    { value: "충청남도", label: "충남 — Chungcheongnam-do" },
    { value: "충청북도", label: "충북 — Chungcheongbuk-do" },
]