export const thailand = [
    { value: "กระบี่", label: "กระบี่ — Krabi" },
    { value: "กรุงเทพมหานคร", label: "กรุงเทพมหานคร — Bangkok" },
    { value: "กาญจนบุรี", label: "กาญจนบุรี — Kanchanaburi" },
    { value: "กาฬสินธุ์", label: "กาฬสินธุ์ — Kalasin" },
    { value: "กำแพงเพชร", label: "กำแพงเพชร — Kamphaeng Phet" },
    { value: "ขอนแก่น", label: "ขอนแก่น — Khon Kaen" },
    { value: "จังหวัด บึงกาฬ", label: "จังหวัด บึงกาฬ — Bueng Kan" },
    { value: "จันทบุรี", label: "จันทบุรี — Chanthaburi" },
    { value: "ฉะเชิงเทรา", label: "ฉะเชิงเทรา — Chachoengsao" },
    { value: "ชลบุรี", label: "ชลบุรี — Chon Buri" },
    { value: "ชัยนาท", label: "ชัยนาท — Chai Nat" },
    { value: "ชัยภูมิ", label: "ชัยภูมิ — Chaiyaphum" },
    { value: "ชุมพร", label: "ชุมพร — Chumpon" },
    { value: "เชียงราย", label: "เชียงราย — Chiang Rai" },
    { value: "เชียงใหม่", label: "เชียงใหม่ — Chiang Mai" },
    { value: "ตรัง", label: "ตรัง — Trang" },
    { value: "ตราด", label: "ตราด — Trat" },
    { value: "ตาก", label: "ตาก — Tak" },
    { value: "นครนายก", label: "นครนายก — Nakhon Nayok" },
    { value: "นครปฐม", label: "นครปฐม — Nakhon Pathom" },
    { value: "นครพนม", label: "นครพนม — Nakhon Phanom" },
    { value: "นครราชสีมา", label: "นครราชสีมา — Nakhon Ratchasima" },
    { value: "นครศรีธรรมราช", label: "นครศรีธรรมราช — Nakhon Si Thammarat" },
    { value: "นครสวรรค์", label: "นครสวรรค์ — Nakhon Sawan" },
    { value: "นนทบุรี", label: "นนทบุรี — Nonthaburi" },
    { value: "นราธิวาส", label: "นราธิวาส — Narathiwat" },
    { value: "น่าน", label: "น่าน — Nan" },
    { value: "บุรีรัมย์", label: "บุรีรัมย์ — Buri Ram" },
    { value: "ปทุมธานี", label: "ปทุมธานี — Pathum Thani" },
    { value: "ประจวบคีรีขันธ์", label: "ประจวบคีรีขันธ์ — Prachuap Khiri Khan" },
    { value: "ปราจีนบุรี", label: "ปราจีนบุรี — Prachin Buri" },
    { value: "ปัตตานี", label: "ปัตตานี — Pattani" },
    { value: "พระนครศรีอยุธยา", label: "พระนครศรีอยุธยา — Phra Nakhon Si Ayutthaya" },
    { value: "พะเยา", label: "พะเยา — Phayao" },
    { value: "พังงา", label: "พังงา — Phang Nga" },
    { value: "พัทลุง", label: "พัทลุง — Phattalung" },
    { value: "พิจิตร", label: "พิจิตร — Phichit" },
    { value: "พิษณุโลก", label: "พิษณุโลก — Phitsanulok" },
    { value: "เพชรบุรี", label: "เพชรบุรี — Phetchaburi" },
    { value: "เพชรบูรณ์", label: "เพชรบูรณ์ — Phetchabun" },
    { value: "แพร่", label: "แพร่ — Phrae" },
    { value: "ภูเก็ต", label: "ภูเก็ต — Phuket" },
    { value: "มหาสารคาม", label: "มหาสารคาม — Maha Sarakham" },
    { value: "มุกดาหาร", label: "มุกดาหาร — Mukdahan" },
    { value: "แม่ฮ่องสอน", label: "แม่ฮ่องสอน — Mae Hong Son" },
    { value: "ยโสธร", label: "ยโสธร — Yasothon" },
    { value: "ยะลา", label: "ยะลา — Yala" },
    { value: "ร้อยเอ็ด", label: "ร้อยเอ็ด — Roi Et" },
    { value: "ระนอง", label: "ระนอง — Ranong" },
    { value: "ระยอง", label: "ระยอง — Rayong" },
    { value: "ราชบุรี", label: "ราชบุรี — Ratchaburi" },
    { value: "ลพบุรี", label: "ลพบุรี — Lop Buri" },
    { value: "ลำปาง", label: "ลำปาง — Lampang" },
    { value: "ลำพูน", label: "ลำพูน — Lamphun" },
    { value: "เลย", label: "เลย — Loei" },
    { value: "ศรีสะเกษ", label: "ศรีสะเกษ — Si Sa Ket" },
    { value: "สกลนคร", label: "สกลนคร — Sakon Nakhon" },
    { value: "สงขลา", label: "สงขลา — Songkhla" },
    { value: "สตูล", label: "สตูล — Satun" },
    { value: "สมุทรปราการ", label: "สมุทรปราการ — Samut Prakan" },
    { value: "สมุทรสงคราม", label: "สมุทรสงคราม — Samut Songkhram" },
    { value: "สมุทรสาคร", label: "สมุทรสาคร — Samut Sakhon" },
    { value: "สระแก้ว", label: "สระแก้ว — Sa Kaeo" },
    { value: "สระบุรี", label: "สระบุรี — Saraburi" },
    { value: "สิงห์บุรี", label: "สิงห์บุรี — Sing Buri" },
    { value: "สุโขทัย", label: "สุโขทัย — Sukhothai" },
    { value: "สุพรรณบุรี", label: "สุพรรณบุรี — Suphanburi" },
    { value: "สุราษฎร์ธานี", label: "สุราษฎร์ธานี — Surat Thani" },
    { value: "สุรินทร์", label: "สุรินทร์ — Surin" },
    { value: "หนองคาย", label: "หนองคาย — Nong Khai" },
    { value: "หนองบัวลำภู", label: "หนองบัวลำภู — Nong Bua Lam Phu" },
    { value: "อ่างทอง", label: "อ่างทอง — Ang Thong" },
    { value: "อำนาจเจริญ", label: "อำนาจเจริญ — Amnat Charoen" },
    { value: "อุดรธานี", label: "อุดรธานี — Udon Thani" },
    { value: "อุตรดิตถ์", label: "อุตรดิตถ์ — Uttaradit" },
    { value: "อุทัยธานี", label: "อุทัยธานี — Uthai Thani" },
    { value: "อุบลราชธานี", label: "อุบลราชธานี — Ubon Ratchathani" },
]