export const ukraine = [
    { value: "Автономна Республіка Крим", label: "Автономна Республіка Крим — Crimea" },
    { value: "Вінницька область", label: "Вінницька область — Vinnyts'ka oblast" },
    { value: "Волинська область", label: "Волинська область — Volyns'ka oblast" },
    { value: "Дніпропетровська область", label: "Дніпропетровська область — Dnipropetrovsk oblast" },
    { value: "Донецька область", label: "Донецька область — Donetsk oblast" },
    { value: "Житомирська область", label: "Житомирська область — Zhytomyrs'ka oblast" },
    { value: "Закарпатська область", label: "Закарпатська область — Zakarpats'ka oblast" },
    { value: "Запорізька область", label: "Запорізька область — Zaporiz'ka oblast" },
    { value: "Івано-Франківська область", label: "Івано-Франківська область — Ivano-Frankivs'ka oblast" },
    { value: "місто Київ", label: "Київ — Kyiv city" },
    { value: "Київська область", label: "Київська область — Kiev oblast" },
    { value: "Кіровоградська область", label: "Кіровоградська область — Kirovohrads'ka oblast" },
    { value: "Луганська область", label: "Луганська область — Luhans'ka oblast" },
    { value: "Львівська область", label: "Львівська область — Lviv oblast" },
    { value: "Миколаївська область", label: "Миколаївська область — Mykolaivs'ka oblast" },
    { value: "Одеська область", label: "Одеська область — Odessa oblast" },
    { value: "Полтавська область", label: "Полтавська область — Poltavs'ka oblast" },
    { value: "Рівненська область", label: "Рівненська область — Rivnens'ka oblast" },
    { value: "місто Севастополь", label: "Севастополь — Sevastopol' city" },
    { value: "Сумська область", label: "Сумська область — Sums'ka oblast" },
    { value: "Тернопільська область", label: "Тернопільська область — Ternopil's'ka oblast" },
    { value: "Харківська область", label: "Харківська область — Kharkiv oblast" },
    { value: "Херсонська область", label: "Херсонська область — Khersons'ka oblast" },
    { value: "Хмельницька область", label: "Хмельницька область — Khmel'nyts'ka oblast" },
    { value: "Черкаська область", label: "Черкаська область — Cherkas'ka oblast" },
    { value: "Чернівецька область", label: "Чернівецька область — Chernivets'ka oblast" },
    { value: "Чернігівська область", label: "Чернігівська область — Chernihivs'ka oblast" },
]