export const uruguay = [
    { value: "Artigas", label: "Artigas" },
    { value: "Canelones", label: "Canelones" },
    { value: "Cerro Largo", label: "Cerro Largo" },
    { value: "Colonia", label: "Colonia" },
    { value: "Durazno", label: "Durazno" },
    { value: "Flores", label: "Flores" },
    { value: "Florida", label: "Florida" },
    { value: "Lavalleja", label: "Lavalleja" },
    { value: "Maldonado", label: "Maldonado" },
    { value: "Montevideo", label: "Montevideo" },
    { value: "Paysandú", label: "Paysandú" },
    { value: "Río Negro", label: "Río Negro" },
    { value: "Rivera", label: "Rivera" },
    { value: "Rocha", label: "Rocha" },
    { value: "Salto", label: "Salto" },
    { value: "San José", label: "San José" },
    { value: "Soriano", label: "Soriano" },
    { value: "Tacuarembó", label: "Tacuarembó" },
    { value: "Treinta y Tres", label: "Treinta y Tres" },
]