export const venezuela = [
    { value: "Amazonas", label: "Amazonas" },
    { value: "Anzoátegui", label: "Anzoátegui" },
    { value: "Apure", label: "Apure" },
    { value: "Aragua", label: "Aragua" },
    { value: "Barinas", label: "Barinas" },
    { value: "Bolívar", label: "Bolívar" },
    { value: "Carabobo", label: "Carabobo" },
    { value: "Cojedes", label: "Cojedes" },
    { value: "Delta Amacuro", label: "Delta Amacuro" },
    { value: "Dependencias Federales", label: "Dependencias Federales" },
    { value: "Distrito Federal", label: "Distrito Federal" },
    { value: "Falcón", label: "Falcón" },
    { value: "Guárico", label: "Guárico" },
    { value: "Lara", label: "Lara" },
    { value: "Mérida", label: "Mérida" },
    { value: "Miranda", label: "Miranda" },
    { value: "Monagas", label: "Monagas" },
    { value: "Nueva Esparta", label: "Nueva Esparta" },
    { value: "Portuguesa", label: "Portuguesa" },
    { value: "Sucre", label: "Sucre" },
    { value: "Táchira", label: "Táchira" },
    { value: "Trujillo", label: "Trujillo" },
    { value: "Vargas", label: "Vargas" },
    { value: "Yaracuy", label: "Yaracuy" },
    { value: "Zulia", label: "Zulia" },
]