export const vietnam = [
    { value: "An Giang", label: "An Giang — An Giang Province" },
    { value: "Bà Rịa–Vũng Tàu", label: "Bà Rịa–Vũng Tàu — Ba Ria-Vung Tau Province" },
    { value: "Bạc Liêu", label: "Bạc Liêu — Bac Lieu Province" },
    { value: "Bắc Giang", label: "Bắc Giang — Bac Giang Province" },
    { value: "Bắc Kạn", label: "Bắc Kạn — Bac Kan Province" },
    { value: "Bắc Ninh", label: "Bắc Ninh — Bac Ninh Province" },
    { value: "Bến Tre", label: "Bến Tre — Ben Tre Province" },
    { value: "Bình Dương", label: "Bình Dương — Binh Duong Province" },
    { value: "Bình Định", label: "Bình Định — Binh Dinh Province" },
    { value: "Bình Phước", label: "Bình Phước — Binh Phuoc Province" },
    { value: "Bình Thuận", label: "Bình Thuận — Binh Thuan Province" },
    { value: "Cà Mau", label: "Cà Mau — Ca Mau Province" },
    { value: "Cao Bằng", label: "Cao Bằng — Cao Bang Province" },
    { value: "Cần Thơ", label: "Cần Thơ — Can Tho City" },
    { value: "Đà Nẵng", label: "Đà Nẵng — Da Nang City" },
    { value: "Đắk Lắk", label: "Đắk Lắk — Dak Lak Province" },
    { value: "Đăk Nông", label: "Đăk Nông — Dak Nong Province" },
    { value: "Điện Biên", label: "Điện Biên — Dien Bien Province" },
    { value: "Đồng Nai", label: "Đồng Nai — Dong Nai Province" },
    { value: "Đồng Tháp", label: "Đồng Tháp — Dong Thap Province" },
    { value: "Gia Lai", label: "Gia Lai — Gia Lai Province" },
    { value: "Hà Giang", label: "Hà Giang — Ha Giang Province" },
    { value: "Hà Nam", label: "Hà Nam — Ha Nam Province" },
    { value: "Hà Nội", label: "Hà Nội — Hanoi City" },
    { value: "Hà Tĩnh", label: "Hà Tĩnh — Ha Tinh Province" },
    { value: "Hải Dương", label: "Hải Dương — Hai Duong Province" },
    { value: "Hải Phòng", label: "Hải Phòng — Haiphong City" },
    { value: "Hậu Giang", label: "Hậu Giang — Hau Giang Province" },
    { value: "Hòa Bình", label: "Hòa Bình — Hoa Binh Province" },
    { value: "Hưng Yên", label: "Hưng Yên — Hung Yen Province" },
    { value: "Khánh Hòa", label: "Khánh Hòa — Khanh Hoa Province" },
    { value: "Kiên Giang", label: "Kiên Giang — Kien Giang Province" },
    { value: "Kon Tum", label: "Kon Tum — Kon Tum Province" },
    { value: "Lai Châu", label: "Lai Châu — Lai Chau Province" },
    { value: "Lạng Sơn", label: "Lạng Sơn — Lang Song Province" },
    { value: "Lào Cai", label: "Lào Cai — Lao Cai Province" },
    { value: "Lâm Đồng", label: "Lâm Đồng — Lam Dong Province" },
    { value: "Long An", label: "Long An — Long An Province" },
    { value: "Nam Định", label: "Nam Định — Nam Dinh Province" },
    { value: "Nghệ An", label: "Nghệ An — Nghe An Province" },
    { value: "Ninh Bình", label: "Ninh Bình — Ninh Binh Province" },
    { value: "Ninh Thuận", label: "Ninh Thuận — Ninh Thuan Province" },
    { value: "Phú Thọ", label: "Phú Thọ — Phu Tho Province" },
    { value: "Phú Yên", label: "Phú Yên — Phu Yen Province" },
    { value: "Quảng Bình", label: "Quảng Bình — Quang Binh Province" },
    { value: "Quảng Nam", label: "Quảng Nam — Quang Nam Province" },
    { value: "Quảng Ngãi", label: "Quảng Ngãi — Quang Ngai Province" },
    { value: "Quảng Ninh", label: "Quảng Ninh — Quang Ninh Province" },
    { value: "Quảng Trị", label: "Quảng Trị — Quang Tri Province" },
    { value: "Sóc Trăng", label: "Sóc Trăng — Soc Trang Province" },
    { value: "Sơn La", label: "Sơn La — Son La Province" },
    { value: "Tây Ninh", label: "Tây Ninh — Tay Ninh Province" },
    { value: "Thái Bình", label: "Thái Bình — Thai Binh Province" },
    { value: "Thái Nguyên", label: "Thái Nguyên — Thai Nguyen Province" },
    { value: "Thanh Hóa", label: "Thanh Hóa — Thanh Hoa Province" },
    { value: "Thành phố Hồ Chí Minh", label: "Thành phố Hồ Chí Minh — Ho Chi Minh City" },
    { value: "Thừa Thiên–Huế", label: "Thừa Thiên–Huế — Thua Thien-Hue Province" },
    { value: "Tiền Giang", label: "Tiền Giang — Tien Giang Province" },
    { value: "Trà Vinh", label: "Trà Vinh — Tra Vinh Province" },
    { value: "Tuyên Quang", label: "Tuyên Quang — Tuyen Quang Province" },
    { value: "Vĩnh Long", label: "Vĩnh Long — Vinh Long Province" },
    { value: "Vĩnh Phúc", label: "Vĩnh Phúc — Vinh Phuc Province" },
    { value: "Yên Bái", label: "Yên Bái — Yen Bai Province" },
]