export const bank = [
    { value: "arzte_und_apotheker_bank", label: "Ärzte- und Apothekerbank" },
    { value: "austrian_anadi_bank_ag", label: "Austrian Anadi Bank AG" },
    { value: "bank_austria", label: "Bank Austria" },
    { value: "bankhaus_carl_spangler", label: "Bankhaus Carl Spängler &amp; Co.AG" },
    { value: "bankhaus_schelhammer_und_schattera_ag", label: "Bankhaus Schelhammer &amp; Schattera AG" },
    { value: "bawag_psk_ag", label: "BAWAG P.S.K. AG" },
    { value: "bks_bank_ag", label: "BKS Bank AG" },
    { value: "brull_kallmus_bank_ag", label: "Brüll Kallmus Bank AG" },
    { value: "btv_vier_lander_bank", label: "BTV VIER LÄNDER BANK" },
    { value: "capital_bank_grawe_gruppe_ag", label: "Capital Bank Grawe Gruppe AG" },
    { value: "dolomitenbank", label: "Dolomitenbank" },
    { value: "easybank_ag", label: "Easybank AG" },
    { value: "erste_bank_und_sparkassen", label: "Erste Bank und Sparkassen" },
    { value: "hypo_alpeadriabank_international_ag", label: "Hypo Alpe-Adria-Bank International AG" },
    { value: "hypo_noe_lb_fur_niederosterreich_u_wien", label: "HYPO NOE LB für Niederösterreich u. Wien" },
    { value: "hypo_oberosterreich_salzburg_steiermark", label: "HYPO Oberösterreich,Salzburg,Steiermark" },
    { value: "hypo_tirol_bank_ag", label: "Hypo Tirol Bank AG" },
    { value: "hypo_vorarlberg_bank_ag", label: "Hypo Vorarlberg Bank AG" },
    { value: "hypo_bank_burgenland_aktiengesellschaft", label: "HYPO-BANK BURGENLAND Aktiengesellschaft" },
    { value: "marchfelder_bank", label: "Marchfelder Bank" },
    { value: "oberbank_ag", label: "Oberbank AG" },
    { value: "raiffeisen_bankengruppe_osterreich", label: "Raiffeisen Bankengruppe Österreich" },
    { value: "schoellerbank_ag", label: "Schoellerbank AG" },
    { value: "sparda_bank_wien", label: "Sparda-Bank Wien" },
    { value: "volksbank_gruppe", label: "Volksbank Gruppe" },
    { value: "volkskreditbank_ag", label: "Volkskreditbank AG" },
    { value: "vr_bank_braunau", label: "VR-Bank Braunau" },
]