export const bank = [
    { value: "alior_bank", label: "Alior Bank" },
    { value: "bank_millennium", label: "Bank Millenium" },
    { value: "bank_nowy_bfg_sa", label: "Bank Nowy BFG S.A." },
    { value: "bank_pekao_sa", label: "Bank PEKAO S.A" },
    { value: "banki_spbdzielcze", label: "Bank spółdzielczy" },
    { value: "blik", label: "BLIK" },
    { value: "bnp_paribas", label: "BNP Paribas" },
    { value: "boz", label: "BOZ" },
    { value: "citi_handlowy", label: "CitiHandlowy" },
    { value: "credit_agricole", label: "Credit Agricole" },
    { value: "etransfer_pocztowy24", label: "e-Transfer Pocztowy24" },
    { value: "getin_bank", label: "Getin Bank" },
    { value: "ideabank", label: "IdeaBank" },
    { value: "ing", label: "ING" },
    { value: "inteligo", label: "inteligo" },
    { value: "mbank_mtransfer", label: "mBank" },
    { value: "nest_przelew", label: "Nest Przelew" },
    { value: "noble_pay", label: "Noble Pay" },
    { value: "pbac_z_ipko", label: "PBac z iPKO (PKO+BP)" },
    { value: "plus_bank", label: "Plus Bank" },
    { value: "santander_przelew24", label: "Santander" },
    { value: "toyota_bank", label: "Toyota Bank" },
    { value: "volkswagen_bank", label: "Volkswagen Bank" },
]
